### ISSUE TITLE
Can I fork/update this ?

### ISSUE THREAD

**Issue by xphlawlessx** [mkremins/TracerySharp#3]
Sorry if this is the wrong channel to ask through, I'm a git-newb, I can't see a licence anywhere but would like to work on/with this project.
firstly I'll update it for the current LTS unity version then have a look at features.
I see it's not been updated in years, I could send pull  requests if you'd still like to be in charge of it or just work on it independently if you're not interested anymore. your call :)

**Comment by mkremins** [comment]
Ah, missed this comment initially – thanks for asking! Definitely feel free to fork, and to send PRs upstream if you want.
